# Generated by Django 2.1.2 on 2018-10-10 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=15)),
                ('pcost', models.DecimalField(decimal_places=4, max_digits=10)),
                ('quantity', models.IntegerField()),
            ],
        ),
    ]
